allowBuilds:
  '@google/genai': true
  '@mongodb-js/zstd': true
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: true
  node-liblzma: true
  protobufjs: true
  sharp: true
  workerd: true
onlyBuiltDependencies: '@google/genai @mongodb-js/zstd node-liblzma protobufjs sharp workerd'
